package com.SBS.Service;

import java.io.FileNotFoundException;

import com.SBS.Impl.TowerFloorFlatImpl;
import com.SBS.interfrace.SocietyInterfrace;


/*
 * input file 
 * 
 * Gurgaon,CHD,T3,F1,101,200
Gurgaon,CHD,T3,F1,102,500
Gurgaon,CHD,T3,F1,103,630
Gurgaon,CHD,T3,F3,301,800
Gurgaon,CHD,T3,F3,302,800
Gurgaon,CHD,T3,F3,303,100
Gurgaon,CHD,T4,F3,201,400
Gurgaon,CHD,T4,F3,202,820
Gurgaon,CHD,T4,F3,303,780
 * 
 * 
 */




public class TowerFloorFlatService {

	
	public static void main(String[] args){
		SocietyInterfrace SocietyInterfrace =new TowerFloorFlatImpl();
		
		 
			try {
				SocietyInterfrace.getBillByTowerNo("T3");
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		
		
		
	}
	
	
	
}



/************* output 
 * 
 * returnedListOfLines [Gurgaon,CHD,T3,F1,101,200, Gurgaon,CHD,T3,F1,102,500, Gurgaon,CHD,T3,F1,103,630, Gurgaon,CHD,T3,F3,301,800, Gurgaon,CHD,T3,F3,302,800, Gurgaon,CHD,T3,F3,303,100, Gurgaon,CHD,T4,F3,201,400, Gurgaon,CHD,T4,F3,202,820, Gurgaon,CHD,T4,F3,303,780]
listOfLines in utility  9
hh Gurgaon
CHD
We have set data into models/pojos 
hh Gurgaon
CHD
We have set data into models/pojos 
hh Gurgaon
CHD
We have set data into models/pojos 
hh Gurgaon
CHD
We have set data into models/pojos 
hh Gurgaon
CHD
We have set data into models/pojos 
hh Gurgaon
CHD
We have set data into models/pojos 
hh Gurgaon
CHD
We have set data into models/pojos 
hh Gurgaon
CHD
We have set data into models/pojos 
hh Gurgaon
CHD
We have set data into models/pojos 
[com.SBS.Model.Society@15db9742, com.SBS.Model.Society@6d06d69c, com.SBS.Model.Society@7852e922, com.SBS.Model.Society@4e25154f, com.SBS.Model.Society@70dea4e, com.SBS.Model.Society@5c647e05, com.SBS.Model.Society@33909752, com.SBS.Model.Society@55f96302, com.SBS.Model.Society@3d4eac69]
tower No:- T3
T3
tower No:- T3
T3
tower No:- T3
T3
tower No:- T3
T3
tower No:- T3
T3
tower No:- T3
T3
tower No:- T4
T3
other than queried tower
tower No:- T4
T3
other than queried tower
tower No:- T4
T3
other than queried tower
total units 3030
**************************************************
total Bill generated by this tower 28785.0 RS/- 
*******************************************************

 * 
 * 
 * 
 * 
 * 
 * 
 * * ***************************/
