package com.SBS.Impl;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.SBS.Model.Society;
import com.SBS.Utility.Utility;
import com.SBS.interfrace.SocietyInterfrace;



public class TowerFloorFlatImpl implements SocietyInterfrace{

	//TowerFloorFlatImpl towerFloorFlatImpl =new TowerFloorFlatImpl();
	private String towerno;
	List<String> returnedListOfLines= new ArrayList<String>();

	public void getBillByTowerNo(String towerNo) throws FileNotFoundException {
		int balance=0;
		double unitRs=9.5;
		try {
			returnedListOfLines=Utility.getListOfInputLinesFromInputFile("C:\\users\\neha\\Desktop\\SocietySample.txt");
			System.out.println("returnedListOfLines "+returnedListOfLines);
			
			List<Society> returnedListOfSocietyObjects=Utility.setValueOfInstanceVariablesIntoObjectsReadFromInputFile(returnedListOfLines);
			System.out.println(returnedListOfSocietyObjects);
			
			for (int j = 0; j < returnedListOfSocietyObjects.size(); j++) {
			Society society=new Society();	
				society=returnedListOfSocietyObjects.get(j);
				
			towerno=society.getTowerNO();
				System.out.println("tower No:- "+towerno);
				System.out.println(towerNo);
				
				if(towerno.equalsIgnoreCase(towerNo)){
					String total=society.getUnits();
				
					balance =balance+(Integer.parseInt(total));
					//System.out.println("blance is "+balance);
					
				}
				else{
					System.out.println("other than queried tower");
				}
			
			}
			
			System.out.println("total units "+balance);
			System.out.println("**************************************************");
			System.out.println("total Bill generated by this tower "+balance * unitRs+" RS/- ");
			System.out.println("*******************************************************");
				
			
			
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		
	}

}
